version: '3.8'

services:
  api:
    build: .
    command: python api/main.py
    env_file:
      - .env
    ports:
      - "${APIPORT}:${APIPORT}"
    volumes:
      - .:/app
    restart: unless-stopped
  redis:
    image: redis:latest
    command: redis-server --save "" --appendonly no
    env_file:
      - .env
    ports:
      - "${REDISPORT}:6379"
    volumes:
      - .:/redis
    restart: unless-stopped
  bot:
    build: .
    command: python -m bot.main
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
